// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class AccountDetail
    {
        public AccountDetail()
        {
            EmpPersonalInfos = new HashSet<EmpPersonalInfo>();
        }

        public int Id { get; set; }
        public int? EmployeeCredentialId { get; set; }
        public string AccountNumber { get; set; }
        public string ConfirmAcNo { get; set; }
        public string IfscCode { get; set; }
        public string ConfirmIfsc { get; set; }
        public string AccountType { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AadharNumber { get; set; }
        public string PfNumber { get; set; }
        public string UanNumber { get; set; }
        public string PfSchema { get; set; }
        public DateTime? PfJoiningDate { get; set; }
        public bool? EligibleForPf { get; set; }

        public virtual EmployeeCredential EmployeeCredential { get; set; }
        public virtual ICollection<EmpPersonalInfo> EmpPersonalInfos { get; set; }
    }
}