// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class AddressInfo
    {
        public int Id { get; set; }
        public int? EmployeeCredentialId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public short? IsActive { get; set; }

        public virtual EmployeeCredential EmployeeCredential { get; set; }
    }
}