// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class Attendance
    {
        public int Id { get; set; }
        public int? EmpCredentialId { get; set; }
        public double? NumberOfHours { get; set; }
        public string Status { get; set; }

        public virtual EmployeeCredential EmpCredential { get; set; }
    }
}