// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class CompanyDetail
    {
        public CompanyDetail()
        {
            Holidays = new HashSet<Holiday>();
            LeaveTypes = new HashSet<LeaveType>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string States { get; set; }
        public string Industry { get; set; }
        public string TimeZone { get; set; }
        public string Currency { get; set; }
        public string PfNo { get; set; }
        public string TanNo { get; set; }
        public string EsiNo { get; set; }
        public string PanNo { get; set; }
        public string GstNo { get; set; }
        public string RegistrationNo { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string LinkedIn { get; set; }
        public string CompanyLogo { get; set; }
        public int? RequestedCompanyId { get; set; }

        public virtual RequestedCompanyForm RequestedCompany { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<LeaveType> LeaveTypes { get; set; }
    }
}