// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class Department
    {
        public Department()
        {
            EmployeeDetails = new HashSet<EmployeeDetail>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? RequestedCompanyId { get; set; }
        public short? IsActive { get; set; }

        public virtual RequestedCompanyForm RequestedCompany { get; set; }
        public virtual ICollection<EmployeeDetail> EmployeeDetails { get; set; }
    }
}