// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class DeviceTable
    {
        public int Id { get; set; }
        public int? EmpCredentialId { get; set; }
        public DateTime? TimeIn { get; set; }
        public DateTime? TimeOut { get; set; }
        public DateTime? InsertedDate { get; set; }

        public virtual EmployeeCredential EmpCredential { get; set; }
    }
}