// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class DeviceTable
    {
        public int Id { get; set; }
        public int? EmpCredentialId { get; set; }
        public TimeSpan? TimeIn { get; set; }
        public TimeSpan? TimeOut { get; set; }
        public DateTime? InsertedDate { get; set; }
        public TimeSpan? WorkTime { get; set; }
        public TimeSpan? OverTime { get; set; }
        public string Remark { get; set; }
        public TimeSpan? ErlOut { get; set; }
        public TimeSpan? LateIn { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }

        public virtual EmployeeCredential EmpCredential { get; set; }
    }
}