// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class DeviceTable
    {
        public int Id { get; set; }
        public int? EmpCode { get; set; }
        public DateTime? TimeIn { get; set; }
        public DateTime? TimeOut { get; set; }
        public DateTime? InsertedDate { get; set; }
        public DateTime? WorkTime { get; set; }
        public DateTime? OverTime { get; set; }
        public string Remark { get; set; }
        public DateTime? ErlOut { get; set; }
        public DateTime? LateIn { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public short? IsActive { get; set; }
    }
}