// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class EmployeeLeaveAllocation
    {
        public int Id { get; set; }
        public int? Year { get; set; }
        public int? EmpCredentialId { get; set; }
        public int? NumberOfLeaves { get; set; }
        public int? RemainingLeave { get; set; }
        public int? LeaveType { get; set; }
        public short? IsActive { get; set; }

        public virtual EmployeeCredential EmpCredential { get; set; }
        public virtual LeaveType LeaveTypeNavigation { get; set; }
    }
}