// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class EmployeeDetail
    {
        public int Id { get; set; }
        public int? DeptId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int? PositionId { get; set; }
        public int? EmployeeCredentialId { get; set; }
        public string EmployeeNumber { get; set; }
        public string Email { get; set; }
        public int? RequestCompanyId { get; set; }

        public virtual Department Dept { get; set; }
        public virtual EmployeeCredential EmployeeCredential { get; set; }
        public virtual Position Position { get; set; }
    }
}