// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class EmployeeCredential
    {
        public EmployeeCredential()
        {
            AccountDetails = new HashSet<AccountDetail>();
            AddressInfos = new HashSet<AddressInfo>();
            EmpPersonalInfos = new HashSet<EmpPersonalInfo>();
            EmpSalaries = new HashSet<EmpSalary>();
            EmployeeAttendances = new HashSet<EmployeeAttendance>();
            EmployeeDetails = new HashSet<EmployeeDetail>();
            EmployeeLeaves = new HashSet<EmployeeLeave>();
            LeaveTypes = new HashSet<LeaveType>();
            UserRolesJs = new HashSet<UserRolesJ>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public short? Status { get; set; }
        public int? RequestedCompanyId { get; set; }
        public string Email { get; set; }
        public bool? DefaultPassword { get; set; }
        public string GenerateOtp { get; set; }
        public DateTime? OtpExpiration { get; set; }

        public virtual RequestedCompanyForm RequestedCompany { get; set; }
        public virtual ICollection<AccountDetail> AccountDetails { get; set; }
        public virtual ICollection<AddressInfo> AddressInfos { get; set; }
        public virtual ICollection<EmpPersonalInfo> EmpPersonalInfos { get; set; }
        public virtual ICollection<EmpSalary> EmpSalaries { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<LeaveType> LeaveTypes { get; set; }
        public virtual ICollection<UserRolesJ> UserRolesJs { get; set; }
    }
}