// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class EmployeeLeave
    {
        public int Id { get; set; }
        public int? EmployeeCredentialId { get; set; }
        public int? LeaveId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Session { get; set; }
        public int? TotalDays { get; set; }
        public string Contact { get; set; }
        public string ReasonForLeave { get; set; }
        public string Files { get; set; }

        public virtual EmployeeCredential EmployeeCredential { get; set; }
        public virtual LeaveType Leave { get; set; }
    }
}