// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class Holiday
    {
        public Holiday()
        {
            EmployeeAttendances = new HashSet<EmployeeAttendance>();
        }

        public int Id { get; set; }
        public string Occasion { get; set; }
        public DateTime? Date { get; set; }
        public string Day { get; set; }
        public bool? RestrictedHoliday { get; set; }
        public int? CompanyId { get; set; }

        public virtual CompanyDetail Company { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
    }
}