// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class Holiday
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public string Type { get; set; }
        public int? CompanyId { get; set; }
        public string Occasion { get; set; }
        public short? IsActive { get; set; }

        public virtual RequestedCompanyForm Company { get; set; }
    }
}