// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HRMS_Application.Models
{
    public partial class HRMSContext : DbContext
    {
        public HRMSContext()
        {
        }

        public HRMSContext(DbContextOptions<HRMSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AccountDetail> AccountDetails { get; set; }
        public virtual DbSet<AddressInfo> AddressInfos { get; set; }
        public virtual DbSet<Aduit> Aduits { get; set; }

        public virtual async Task<int> SaveChangesAsync(int? userId = null)
        {
            OnBeforeSaveChanges(userId);
            var result = await base.SaveChangesAsync();
            return result;
        }

        private void OnBeforeSaveChanges(int? userId)
        {
            ChangeTracker.DetectChanges();
            var auditEntries = new List<AuditEntry>();
            foreach (var entry in ChangeTracker.Entries())
            {
                if (entry.Entity is Aduit || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                    continue;

                var auditEntry = new AuditEntry(entry);
                auditEntry.TableName = entry.Entity.GetType().Name;
                auditEntry.UserId = userId;
                auditEntries.Add(auditEntry);

                foreach (var property in entry.Properties)
                {
                    string propertyName = property.Metadata.Name;
                    if (property.Metadata.IsPrimaryKey())
                    {
                        auditEntry.KeyValues[propertyName] = property.CurrentValue;
                        continue;
                    }

                    switch (entry.State)
                    {
                        case EntityState.Added:
                            auditEntry.AuditType = Enums.AuditType.Create;
                            auditEntry.NewValues[propertyName] = property.CurrentValue;
                            break;
                        case EntityState.Deleted:
                            auditEntry.AuditType = Enums.AuditType.Delete;
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                            break;
                        case EntityState.Modified:
                            if (property.IsModified)
                            {
                                auditEntry.ChangedColumns.Add(propertyName);
                                auditEntry.AuditType = Enums.AuditType.Update;
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                            break;
                    }
                }
            }
        }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmpPersonalInfo> EmpPersonalInfos { get; set; }
        public virtual DbSet<EmpSalary> EmpSalaries { get; set; }
        public virtual DbSet<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual DbSet<EmployeeCredential> EmployeeCredentials { get; set; }
        public virtual DbSet<EmployeeDetail> EmployeeDetails { get; set; }
        public virtual DbSet<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<RequestedCompanyForm> RequestedCompanyForms { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRolesJ> UserRolesJs { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AccountDetail>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AadharNumber)
                    .HasMaxLength(12)
                    .IsUnicode(false);

                entity.Property(e => e.AccountNumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.AccountType)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.BankName)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.BranchName)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.ConfirmAcNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("Confirm_Ac_No");

                entity.Property(e => e.ConfirmIfsc)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("Confirm_IFSC");

                entity.Property(e => e.EligibleForPf).HasColumnName("EligibleForPF");

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.IfscCode)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("IFSC_Code");

                entity.Property(e => e.PfJoiningDate)
                    .HasColumnType("date")
                    .HasColumnName("PF_joiningDate");

                entity.Property(e => e.PfNumber)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("PF_Number");

                entity.Property(e => e.PfSchema)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("PF_Schema");

                entity.Property(e => e.UanNumber)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("UAN_Number");

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.AccountDetails)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__AccountDe__Emplo__6B24EA82");
            });

            modelBuilder.Entity<AddressInfo>(entity =>
            {
                entity.ToTable("AddressInfo");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AddressLine1)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.AddressLine2)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.City)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Country)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.PinCode)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("PIN_Code");

                entity.Property(e => e.State)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.AddressInfos)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__AddressIn__Emplo__6C190EBB");
            });

            modelBuilder.Entity<Aduit>(entity =>
            {
                entity.ToTable("Aduit");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.AffectedColumns)
                    .HasMaxLength(4000)
                    .IsUnicode(false);

                entity.Property(e => e.DateTime).HasColumnType("datetime");

                entity.Property(e => e.NewValues)
                    .IsUnicode(false)
                    .HasColumnName("newValues");

                entity.Property(e => e.OldValues)
                    .IsUnicode(false)
                    .HasColumnName("oldValues");

                entity.Property(e => e.PrimaryKey)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.TableName)
                    .HasMaxLength(500)
                    .IsUnicode(false);

                entity.Property(e => e.Type)
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<CompanyDetail>(entity =>
            {
                entity.ToTable("Company_Details");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Address)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Country)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Currency)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EsiNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ESI_No");

                entity.Property(e => e.Facebook)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.GstNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("GST_No");

                entity.Property(e => e.Industry)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.LinkedIn)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.PanNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("PAN_No");

                entity.Property(e => e.PfNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("PF_No");

                entity.Property(e => e.RegistrationNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("Registration_No");

                entity.Property(e => e.RequestedCompanyId).HasColumnName("Requested_Company_id");

                entity.Property(e => e.States)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.TanNo)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("TAN_No");

                entity.Property(e => e.TimeZone)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Twitter)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.RequestedCompany)
                    .WithMany(p => p.CompanyDetails)
                    .HasForeignKey(d => d.RequestedCompanyId)
                    .HasConstraintName("FK__Company_D__Reque__6D0D32F4");
            });

            modelBuilder.Entity<Department>(entity =>
            {
                entity.ToTable("Department");

                entity.HasIndex(e => e.RequestedCompanyId, "UQ__Departme__E20112F66B20A0D2")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Name)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.RequestedCompanyId).HasColumnName("Requested_Company_id");

                entity.HasOne(d => d.RequestedCompany)
                    .WithOne(p => p.Department)
                    .HasForeignKey<Department>(d => d.RequestedCompanyId)
                    .HasConstraintName("FK__Departmen__Reque__6E01572D");
            });

            modelBuilder.Entity<EmpPersonalInfo>(entity =>
            {
                entity.ToTable("EmpPersonal_Info");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.BloodGroup)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ConfirmDate).HasColumnType("date");

                entity.Property(e => e.DateOfJoining).HasColumnType("date");

                entity.Property(e => e.Dob)
                    .HasColumnType("date")
                    .HasColumnName("DOB");

                entity.Property(e => e.EmailId)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("Email_Id");

                entity.Property(e => e.EmergencyContact)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EmpStatus)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.MaritalStatus)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PersonalEmail)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.SpouseName)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.Account)
                    .WithMany(p => p.EmpPersonalInfos)
                    .HasForeignKey(d => d.AccountId)
                    .HasConstraintName("FK__EmpPerson__Accou__778AC167");

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.EmpPersonalInfos)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__EmpPerson__Emplo__787EE5A0");
            });

            modelBuilder.Entity<EmpSalary>(entity =>
            {
                entity.ToTable("EmpSalary");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.AnnualIncome)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("Annual_Income");

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.Insurance).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Loan).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SalaryRange)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.EmpSalaries)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__EmpSalary__Emplo__797309D9");
            });

            modelBuilder.Entity<EmployeeAttendance>(entity =>
            {
                entity.ToTable("EmployeeAttendance");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.HolidayId).HasColumnName("Holiday_id");

                entity.Property(e => e.LeaveId).HasColumnName("Leave_id");

                entity.Property(e => e.Remarks)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.TimeIn).HasColumnType("datetime");

                entity.Property(e => e.TimeOut).HasColumnType("datetime");

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.EmployeeAttendances)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__EmployeeA__Emplo__72C60C4A");

                entity.HasOne(d => d.Holiday)
                    .WithMany(p => p.EmployeeAttendances)
                    .HasForeignKey(d => d.HolidayId)
                    .HasConstraintName("FK__EmployeeA__Holid__73BA3083");

                entity.HasOne(d => d.Leave)
                    .WithMany(p => p.EmployeeAttendances)
                    .HasForeignKey(d => d.LeaveId)
                    .HasConstraintName("FK__EmployeeA__Leave__74AE54BC");
            });

            modelBuilder.Entity<EmployeeCredential>(entity =>
            {
                entity.ToTable("Employee_Credential");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.DefaultPassword).HasColumnName("Default_Password");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.GenerateOtp)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Generate_OTP");

                entity.Property(e => e.OtpExpiration)
                    .HasColumnType("datetime")
                    .HasColumnName("Otp_Expiration");

                entity.Property(e => e.Password).HasMaxLength(256);

                entity.Property(e => e.RequestedCompanyId).HasColumnName("Requested_Company_id");

                entity.Property(e => e.UserName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.RequestedCompany)
                    .WithMany(p => p.EmployeeCredentials)
                    .HasForeignKey(d => d.RequestedCompanyId)
                    .HasConstraintName("FK__Employee___Reque__6EF57B66");
            });

            modelBuilder.Entity<EmployeeDetail>(entity =>
            {
                entity.ToTable("Employee_Detail");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Designation)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.EmployeeNumber)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.FirstName)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.LastName)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.MiddleName)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.RequestCompanyId).HasColumnName("Request_Company_Id");

                entity.HasOne(d => d.Dept)
                    .WithMany(p => p.EmployeeDetails)
                    .HasForeignKey(d => d.DeptId)
                    .HasConstraintName("FK__Employee___DeptI__6FE99F9F");

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.EmployeeDetails)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__Employee___Emplo__70DDC3D8");

                entity.HasOne(d => d.Position)
                    .WithMany(p => p.EmployeeDetails)
                    .HasForeignKey(d => d.PositionId)
                    .HasConstraintName("FK__Employee___Posit__71D1E811");
            });

            modelBuilder.Entity<EmployeeLeave>(entity =>
            {
                entity.ToTable("EmployeeLeave");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Contact)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.EndDate).HasColumnType("date");

                entity.Property(e => e.LeaveId).HasColumnName("Leave_id");

                entity.Property(e => e.ReasonForLeave)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Session)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StartDate).HasColumnType("date");

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.EmployeeLeaves)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__EmployeeL__Emplo__75A278F5");

                entity.HasOne(d => d.Leave)
                    .WithMany(p => p.EmployeeLeaves)
                    .HasForeignKey(d => d.LeaveId)
                    .HasConstraintName("FK__EmployeeL__Leave__76969D2E");
            });

            modelBuilder.Entity<File>(entity =>
            {
                entity.Property(e => e.FileUrl).IsUnicode(false);

                entity.Property(e => e.IsActive).HasColumnName("isActive");

                entity.Property(e => e.ObjectName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Tags).IsUnicode(false);
            });

            modelBuilder.Entity<Holiday>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CompanyId).HasColumnName("Company_id");

                entity.Property(e => e.Date).HasColumnType("date");

                entity.Property(e => e.Occasion)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Type)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Holidays)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_Holiday_Company");
            });

            modelBuilder.Entity<LeaveType>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CompanyId).HasColumnName("Company_id");

                entity.Property(e => e.EmployeecredentialId).HasColumnName("employeecredentialId");

                entity.Property(e => e.LeaveType1)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("LeaveType");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.LeaveTypes)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK__LeaveType__Compa__7B5B524B");

                entity.HasOne(d => d.Employeecredential)
                    .WithMany(p => p.LeaveTypes)
                    .HasForeignKey(d => d.EmployeecredentialId)
                    .HasConstraintName("FK_LeaveTypes_EmployeeCredentials");
            });

            modelBuilder.Entity<Position>(entity =>
            {
                entity.ToTable("Position");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Name)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.RequestedCompanyId).HasColumnName("Requested_Company_id");

                entity.HasOne(d => d.RequestedCompany)
                    .WithMany(p => p.Positions)
                    .HasForeignKey(d => d.RequestedCompanyId)
                    .HasConstraintName("FK__Position__Reques__7D439ABD");
            });

            modelBuilder.Entity<RequestedCompanyForm>(entity =>
            {
                entity.ToTable("Requested_company_form");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.DomainName)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("Domain_name");

                entity.Property(e => e.Email)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.InsertedDate).HasColumnType("datetime");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PhoneNumber)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("Phone_number");

                entity.Property(e => e.Status)
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<Role>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<UserRolesJ>(entity =>
            {
                entity.ToTable("User_Roles_J");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.EmployeeCredentialId).HasColumnName("Employee_Credential_Id");

                entity.Property(e => e.RolesId).HasColumnName("Roles_Id");

                entity.HasOne(d => d.EmployeeCredential)
                    .WithMany(p => p.UserRolesJs)
                    .HasForeignKey(d => d.EmployeeCredentialId)
                    .HasConstraintName("FK__User_Role__Emplo__7E37BEF6");

                entity.HasOne(d => d.Roles)
                    .WithMany(p => p.UserRolesJs)
                    .HasForeignKey(d => d.RolesId)
                    .HasConstraintName("FK_Roles");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}