// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HRMS_Application.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace HRMS_Application.Models
{
    public partial interface IHRMSContextProcedures
    {
        Task<int> AttendanceStatusUpdateAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateAttendanceAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateAttendanceStatuAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateAttendanceStatusAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
