// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HRMS_Application.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace HRMS_Application.Models
{
    public partial interface IHRMSContextProcedures
    {
        Task<List<NewUpdateProcedureResult>> NewUpdateProcedureAsync(int? Company_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> TableUpdationAsync(int? Company_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateDeviceTableAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateEmployeeAttendanceDetailsAsync(int? Company_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
