// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class LeaveType
    {
        public LeaveType()
        {
            EmployeeAttendances = new HashSet<EmployeeAttendance>();
            EmployeeLeaves = new HashSet<EmployeeLeave>();
        }

        public int Id { get; set; }
        public string LeaveType1 { get; set; }
        public int? Days { get; set; }
        public int? CompanyId { get; set; }

        public virtual CompanyDetail Company { get; set; }
        public virtual ICollection<EmployeeAttendance> EmployeeAttendances { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
    }
}