// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class NewsPreview
    {
        public NewsPreview()
        {
            News = new HashSet<News>();
        }

        public int Id { get; set; }
        public DateTime? DisplayDate { get; set; }
        public DateTime? InsertedDate { get; set; }
        public string Heading { get; set; }
        public string Desciption { get; set; }
        public string ImgUrl { get; set; }
        public short? IsActive { get; set; }

        public virtual ICollection<News> News { get; set; }
    }
}