// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class News
    {
        public int Id { get; set; }
        public int? NewsPreviewId { get; set; }
        public string Heading { get; set; }
        public string Details { get; set; }

        public virtual NewsPreview NewsPreview { get; set; }
    }
}