// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class OrganizationWorkingDay
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public bool M { get; set; }
        public bool T { get; set; }
        public bool W { get; set; }
        public bool Th { get; set; }
        public bool F { get; set; }
        public bool Sa { get; set; }
        public bool Su { get; set; }

        public virtual RequestedCompanyForm Company { get; set; }
    }
}