// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class RequestedCompanyForm
    {
        public RequestedCompanyForm()
        {
            CompanyDetails = new HashSet<CompanyDetail>();
            Departments = new HashSet<Department>();
            EmployeeCredentials = new HashSet<EmployeeCredential>();
            Holidays = new HashSet<Holiday>();
            LeaveTypes = new HashSet<LeaveType>();
            Positions = new HashSet<Position>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string DomainName { get; set; }
        public string Status { get; set; }
        public DateTime? InsertedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Email { get; set; }

        public virtual ICollection<CompanyDetail> CompanyDetails { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<EmployeeCredential> EmployeeCredentials { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<LeaveType> LeaveTypes { get; set; }
        public virtual ICollection<Position> Positions { get; set; }
    }
}