// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class ResignationApprovalStatus
    {
        public int Id { get; set; }
        public int? ResignationId { get; set; }
        public string ManagerApprovalStatus { get; set; }
        public string AdminApprovalStatus { get; set; }
        public short? IsActive { get; set; }

        public virtual Resignation Resignation { get; set; }
    }
}