// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class Resignation
    {
        public Resignation()
        {
            ResignationApprovalStatuses = new HashSet<ResignationApprovalStatus>();
        }

        public int Id { get; set; }
        public int? EmpCredentialId { get; set; }
        public string Reason { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? ExitDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Status { get; set; }
        public DateTime? FinalSettlementDate { get; set; }
        public short? IsActive { get; set; }
        public string Comments { get; set; }

        public virtual ICollection<ResignationApprovalStatus> ResignationApprovalStatuses { get; set; }
    }
}