// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class Role
    {
        public Role()
        {
            UserRolesJs = new HashSet<UserRolesJ>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public short? IsActive { get; set; }

        public virtual ICollection<UserRolesJ> UserRolesJs { get; set; }
    }
}