// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HRMS_Application.Models
{
    public partial class ShiftRoster
    {
        public int Id { get; set; }
        public int? EmpCredentialId { get; set; }
        public int? ShiftRosterTypeId { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Enddate { get; set; }

        public virtual ShiftRosterType ShiftRosterType { get; set; }
    }
}